include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    prefer_asserts_with_message: false
    omit_local_variable_types: false
    avoid_dynamic_calls: false
    avoid_positional_boolean_parameters: false
    unnecessary_await_in_return: false
    use_if_null_to_convert_nulls_to_bools: false
    no_default_cases: false
    cascade_invocations: false
    flutter_style_todos: false
    unawaited_futures: false
    avoid_void_async: false
    avoid_field_initializers_in_const_classes: false
    unnecessary_breaks: false

analyzer:
  errors:
    strict_raw_type: ignore
    invalid_annotation_target: ignore
    inference_failure_on_function_return_type: ignore
    inference_failure_on_untyped_parameter: ignore
    inference_failure_on_instance_creation: ignore
    inference_failure_on_function_invocation: ignore
    inference_failure_on_collection_literal: ignore
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.gen.dart
    - lib/**/*.freezed.dart
    - lib/**/*.chopper.dart
    - lib/**/*.config.dart
    - build/**
    - test/test_util/test_dependencies.config.dart
    - lib/utils/data/card_names.dart
    - lib/utils/data/printed_name_to_id.dart
    - scripts/assets/**