name: MoxifyMTG
description: "Moxify MTG - Collect - Scan - Track."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  dynamic_color: ^1.6.9
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1


dev_dependencies:  
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/