name: MoxifyMTG
description: "Moxify MTG - Collect - Scan - Track."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  auto_route: ^9.3.0+1
  dynamic_color: ^1.6.9
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  flutter_web_plugins:
    sdk: flutter
  google_fonts: ^6.2.1
  js: ^0.7.1
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.1
  url_launcher_web: ^2.4.0


dev_dependencies:  
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/backdrop/
    - assets/badges/